#!/bin/sh
# verify_env.sh : prove the pinned FGO toolchain can build and run GTSAM code.
#
#   tools/fgo/verify_env.sh [build-dir]
#
# Builds tools/fgo/gtsam_smoke with tools/fgo/fgo-toolchain.cmake and runs it.
# On success it writes <build-dir>/fgo_toolchain.txt, the metadata that
# plan.md 11.1 P1.3 requires to accompany any byte-diff baseline.
#
# Exit status is non-zero if any part of the toolchain is unusable.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
build=${1:-$here/gtsam_smoke/build}

prefix=${FGO_ENV_PREFIX:-${CONDA_PREFIX:-$HOME/miniconda3/envs/rtklib-fgo}}
cc=${FGO_CC:-/usr/bin/gcc}
cxx=${FGO_CXX:-/usr/bin/g++}
cmake_bin=${FGO_CMAKE:-$prefix/bin/cmake}

[ -x "$cmake_bin" ] || {
    echo "verify_env.sh: cmake not found at $cmake_bin" >&2
    echo "               run tools/fgo/setup_env.sh first" >&2
    exit 1
}

echo "== toolchain =="
echo "  env prefix : $prefix"
echo "  cc         : $cc"
echo "  cxx        : $cxx"
echo "  cmake      : $cmake_bin"
echo

FGO_ENV_PREFIX=$prefix FGO_CC=$cc FGO_CXX=$cxx \
    "$cmake_bin" -S "$here/gtsam_smoke" -B "$build" -G Ninja \
        --toolchain "$here/fgo-toolchain.cmake" \
        -DCMAKE_BUILD_TYPE=Release >/dev/null
"$cmake_bin" --build "$build" >/dev/null

echo "== capability probe =="
"$build/gtsam_smoke"

# ---- record what actually got used (plan.md 11.1 P1.3) ----------------------
meta=$build/fgo_toolchain.txt
{
    echo "# RTKLIB FGO toolchain metadata"
    echo "# generated by tools/fgo/verify_env.sh -- do not edit"
    echo "git-commit   : $(git -C "$here" rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "env-prefix   : $prefix"
    echo "cc           : $cc"
    echo "cc-version   : $("$cc" --version | head -1)"
    echo "cxx          : $cxx"
    echo "cxx-version  : $("$cxx" --version | head -1)"
    echo "cmake        : $("$cmake_bin" --version | head -1)"
    echo "uname        : $(uname -srm)"
    echo "libc         : $(ldd --version 2>/dev/null | head -1)"
    echo "# --- conda packages ---"
    conda list -p "$prefix" 2>/dev/null |
        grep -E '^(gtsam|eigen|libboost-devel|tbb|libstdcxx|metis|cmake|ninja|python|numpy) ' ||
        echo "(conda not available)"
} > "$meta"

echo
echo "toolchain metadata written to $meta"
